# Generated by Django 2.0.5 on 2018-05-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityzip',
            name='zip',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
